app/src/main/res/drawable/ic_circle.xml, app/src/main/res/layout/fragment_onboarding_permission.xml, app/src/main/res/layout/item_permission.xml, app/src/main/res/values/strings.xml
=> 5 feature onboarding 권한 #5

app/src/main/res/layout/fragment_group_join.xml, app/src/main/res/values/strings.xml
그룹에 대한 상세화면으로,
홈 화면에서 그룹에 대한 탭을 누르면 이동할 수 있는 화면
=> Group 상세 화면 구현 #9

app/src/main/res/drawable/bg_rounded_group_1.xml, app/src/main/res/drawable/bg_rounded_group_2.xml, app/src/main/res/drawable/bg_rounded_group_3.xml, app/src/main/res/drawable/bg_rounded_group_4.xml, app/src/main/res/drawable/bg_rounded_group_5.xml, app/src/main/res/layout/fragment_make_group.xml, app/src/main/res/values/strings.xml
=> 그룹 만들기 화면 UI 제작 #17

app/src/main/res/drawable/bg_rounded_fit_off.xml, app/src/main/res/layout/fragment_group_fit_off.xml, app/src/main/res/layout/item_fit_off.xml, app/src/main/res/values/strings.xml
여기서 쓰이는 item_fit_off는 추후에 MyFit 화면에서 이동 가능한 화면 중,
나의 피트오프 열람 내역을 보여주는 화면에서
ItemView의 재사용이 가능하다 생각하여 네임 컨벤션 당시에 고려하여 이름을 통일하였습니다.
=> 그룹 내 피트오프 열람 화면 UI 구현 #19

app/src/main/res/drawable/bg_rounded_group_6.xml, app/src/main/res/layout/fragment_make_fit_off.xml, app/src/main/res/values/strings.xml
해당 화면에서 추후 구현 시,
특정 카테고리에 대해서
사유가 있을 경우, 질병이 없는 것으로 판단해, 진단서 제출 탭이 Invisible 되며,
질병이 있을 경우, 사유가 없는 것으로 판단해, 사유 탭이 Invisible 됨
=> 그룹 내 피트오프 신청 화면 UI 구현 #21

app/build.gradle.kts, app/src/main/java/com/fitmate/fitmate/MainActivity.kt, app/src/main/java/com/fitmate/fitmate/ui/home/HomeCategoryFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/home/HomeMainFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/login/LoginFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/mygroup/MyGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingFirstFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingPermissionFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingSecondFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/onboarding/OnBoardingThirdFragment.kt, app/src/main/java/com/fitmate/fitmate/ui/userinfo/LisenceFragment.kt, app/src/main/res/layout/activity_main.xml, app/src/main/res/menu/menu_main_bottom_navigation.xml, app/src/main/res/navigation/nav_main_graph.xml, app/src/main/res/values/strings.xml, buildSrc/src/main/kotlin/Libraries.kt, buildSrc/src/main/kotlin/Versions.kt
메인 액티비티의 바텀 네비게이션을 navigation 라이브러리를 활용하여 프래그먼트와 연결
=> 바텀 네비게이션 화면 전환 구현 #24

app/src/main/java/com/fitmate/fitmate/ChatActivity.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupFineFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupFitOffFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupProgressFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupVoteFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/MakeFitOffFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupFineViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupFitOffViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupVoteViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupFineAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupFitOffAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupProgressAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupProgressViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupVoteAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/GroupJoinFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeMainFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/VoteViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/CertificateFragment.kt, app/src/main/res/layout/activity_chat.xml, app/src/main/res/layout/fragment_chatting.xml, app/src/main/res/layout/fragment_group_fine.xml, app/src/main/res/layout/fragment_group_fit_off.xml, app/src/main/res/layout/fragment_group_vote.xml, app/src/main/res/layout/fragment_make_fit_off.xml, app/src/main/res/layout/fragment_progress.xml, app/src/main/res/navigation/nav_chat_graph.xml, app/src/main/res/navigation/nav_main_graph.xml, app/src/main/res/values/strings.xml
=> 채팅 화면 연결 작업 #24

app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/res/layout/dialog_user_thumbnail.xml
유저 프로필 firebase 서버에 업데이트
프로필 사진 변경 시 변경 기능 추가
=> 유저 프로필 업데이트 서버 연결 #2

app/build.gradle.kts, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/res/layout/fragment_login_webview.xml, app/src/main/res/navigation/nav_main_graph.xml
네이버, 카카오에서 Authorization 코드 받아오기 기능 구현
local.properties에 API_KEY 숨김
코드 서버에 전송 및 로그인 완료 후 닉네임 설정, 유저 회원정보 변경 등
필요한 내용들은 추후 서버와 연결 후 제작 예정
=> Login 기능 구현 #11

app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/DayViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MonthViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/DayListAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MonthListAdapter.kt, app/src/main/res/drawable/bg_border_default.xml, app/src/main/res/drawable/bg_border_selected.xml, app/src/main/res/layout/fragment_group_join.xml, app/src/main/res/layout/fragment_myfit.xml, app/src/main/res/layout/item_list_day.xml, app/src/main/res/layout/item_list_month.xml
커스텀 캘린더 구현 및 fab(최상단으로 스크롤)구현 완료
=> my fit 커스텀 캘린더 구현 완료 #15

app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupProgressFragment.kt, app/src/main/res/layout/item_progress.xml, app/src/main/res/values/strings.xml
=> my fit, 그룹 fit현황 progress text추가 완료 #15 #28

app/src/main/java/com/fitmate/fitmate/data/model/CertificationMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/CertificationRecordDto.kt, app/src/main/java/com/fitmate/fitmate/data/model/entity/CertificationEntity.kt, app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRecordRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/CertificationConverters.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/CertificationRecordService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/CertificationNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/NetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/RetrofitModule.kt, app/src/main/java/com/fitmate/fitmate/domain/model/CertificationRecord.kt, app/src/main/java/com/fitmate/fitmate/domain/model/DbCertification.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/CertificationRecordRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/CertificationRecordNetworkUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt
=> 인증 네트워크 post 구현 완료 #34

app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/list/adapter/CertificationImageAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt, app/src/main/res/layout/fragment_certificate.xml
=> 인증 오류 수정 및 그룹 선택 다이얼로그를 통한 그룹 선택 준비 완료 #34

app/src/main/java/com/fitmate/fitmate/data/model/CertificationMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/CertificationRecordDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRecordRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/CertificationRecordService.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/CertificationTargetGroupService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/CertificationNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/RetrofitModule.kt, app/src/main/java/com/fitmate/fitmate/domain/model/CertificationNetworkResponse.kt, app/src/main/java/com/fitmate/fitmate/domain/model/CertificationRecord.kt, app/src/main/java/com/fitmate/fitmate/domain/model/ResisterCertificationRecord.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/CertificationRecordRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/CertificationRecordNetworkUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt
인증 구현 완료 되었으며 추후 release를 통해 고도화 예정입니다 
+알 수 없는 오류가 발생되어서 해당 오류는 해결 예정.
=> 인증 기능 구현 완료 PR(release1) #34

app/src/main/java/com/fitmate/fitmate/domain/model/LicenseItem.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/LicenseFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/list/LicenseData.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/list/LicenseViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/list/adapter/LicenseAdapter.kt, app/src/main/res/layout/fragment_license.xml, app/src/main/res/layout/item_license.xml, app/src/main/res/values/strings.xml
사용했던 오픈소스 라이브러리 아이템 추가
추후에 백앤드 측 혹은 안드로이드에서 추가 사용한 기능들 있을 시,
LicenseData에 추후 추가
추가로 구현을 미룬 FitOff 기능에 대한 제한 추가
=> 오픈소스 라이선스 고지 아이템 추가 #2

app/src/main/java/com/fitmate/fitmate/data/model/MyFitMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/MyFitProgressDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/MyFitRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/MyFitService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/MyFitNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/domain/model/FitProgressItem.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/MyFitRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/MyFitUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupProgressFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupProgressAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupProgressViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MyFitGroupProgressViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MyFitGroupProgressAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/MtFitViewModel.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/MyFitViewModel.kt, app/src/main/java/com/fitmate/fitmate/util/BindingAdapter.kt, app/src/main/res/anim/progress_fill_animation.xml, app/src/main/res/layout/fragment_home_main.xml, app/src/main/res/layout/fragment_myfit.xml, app/src/main/res/layout/item_fit_grogress_shimmer.xml, app/src/main/res/layout/item_progress.xml
마이 피트 통신 및 애니매이션 구현 완료 및 홈 프래그먼트 스크롤 수정
=> 마이 피트 통신 및 애니매이션 구현 #15

app/src/main/java/com/fitmate/fitmate/data/model/dto/GroupDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/GroupRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/GroupService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/ChatModule.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/GroupRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/GroupUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupProgressFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupProgressViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/FitMateListAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/GroupViewModel.kt, app/src/main/res/layout/fragment_chatting.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/item_chatting_fit_mate.xml, app/src/main/res/layout/item_progress.xml, app/src/main/res/values/strings.xml
[1] Drawer 내부 화면 본인 프로필 & 그룹 내 메이트들 명단 추가
[2] 플러스 버튼 FIT 현황 구현 - 메이트들 이번 주 운동 현황
=> 채팅 플러스 메뉴 구현(2) #30 

app/src/main/java/com/fitmate/fitmate/data/model/dto/GroupDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/GroupRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/GroupService.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/GroupRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/GroupUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupVoteFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupVoteViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/adapter/GroupVoteAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/GroupViewModel.kt
mock api를 통해서
그룹 투표 현황화면에서 투표 내용을 확인하고
그에 대한 찬성/거절 여부를 서버에 올려주는 기능 구현
추후 서버에 연결 시 실 서버로 변경 예정
=> 투표 선택 서버에 전달 #31

app/src/main/java/com/fitmate/fitmate/data/model/MyFitMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/FitRecordHistoryDto.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/MyFitDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/MyFitRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/GroupService.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/MyFitService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/MyFitNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/domain/model/MyFitRecordHistory.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/MyFitRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/MyFitUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/DayViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MonthViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/MyFitHistoryViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/DayListAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MonthListAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/adapter/MyFitHistoryAdapter.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/MyFitViewModel.kt, app/src/main/java/com/fitmate/fitmate/util/BindingAdapter.kt, app/src/main/res/layout/fragment_myfit.xml, app/src/main/res/layout/item_my_fit_history.xml
=> 15 feature myfit화면 캘린더 및 운동 기록 release1 구현 완료

app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt
Android 13 버전 이후부터,
기존의 갤러리로 들어가서 이미지를 가져오는 것이 아닌,
photo picker를 통해서 가져오도록 변경
=> Fix upload profile image to photo picker

app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/repository/MakeFitGroupRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/MakeFitGroupNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/storageModule/StorageReferencesModule.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/MakeFitGroupRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/MakeFitGroupUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/MakeGroupViewModel.kt, app/src/main/res/layout/fragment_make_group.xml
그룹 생성 화면 유효성 검사 및 스토리지에 사진 업로드 구현 완료
+ 백엔드에 post작업 예정
=> Feat add upload images to strorage at make group screen #17

app/src/main/java/com/fitmate/fitmate/data/source/remote/CertificationTargetGroupService.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/MyFitService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/CertificationNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/res/navigation/nav_main_graph.xml
가입된 그룹이 없을 경우 다이얼로그로 가입하러 이동할지 리셋하고 유지할지 결정하는 로직 구현완료
mock서버 에러로 인해 내가 구현한 서버 링크 긴급 수정 완료
=> 운동 기록 화면 구현 피트 그룹 이슈 해결 및 목데이터 링크 수정 #34

app/src/main/java/com/fitmate/fitmate/data/source/remote/MyFitService.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/res/layout/fragment_myfit.xml, app/src/main/res/navigation/nav_main_graph.xml
마이 피트 화면 그룹 가입하러 가기 클릭 리스너 및 로직 구현 완료
=> feature myfit화면 그룹가입하러가기 #15

app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/list/DayViewHolder.kt, app/src/main/java/com/fitmate/fitmate/util/BindingAdapter.kt, app/src/main/res/drawable/baseline_vertical_align_top_24.xml, app/src/main/res/layout/bank_bottom_sheet.xml, app/src/main/res/layout/fragment_certificate.xml, app/src/main/res/layout/fragment_make_group.xml, app/src/main/res/layout/fragment_myfit.xml, app/src/main/res/layout/item_bank_list_grid.xml, app/src/main/res/navigation/nav_main_graph.xml
myFit 화면캘린더 빈 박스 테투리 설정 이슈 해결
myFit 화면 플로팅 버튼 아이콘 및 버튼(피트오프, 기록하기) 글씨체 설정
운동 기록 화면 인증취소 글씨체 변경
운동 기록 화면 다이얼로그 글씨체
그룹 생성 화면 바텀 시트 리사이클러뷰 글씨체 및 설정 안된 글씨체 적용하기
=> 디자인 및 사소한 이슈 해결 #86

app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeCategoryFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeMainFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/adapter/CarouselAdapter.kt, app/src/main/res/layout/fragment_home_category.xml, app/src/main/res/layout/fragment_home_main.xml, app/src/main/res/layout/item_category.xml, app/src/main/res/layout/item_main_carousel.xml, app/src/main/res/layout/item_vote.xml
1) Carousel Adapter 방식 결졍 & 예시 데이터 삽입
2) 홈 화면 글씨 크기에 대한 구속조건 변경
3) 탭 이동 간 통신 매커니즘 변경
=> 홈 화면 디자인 및 통신 방식 조정 #3

app/src/main/java/com/fitmate/fitmate/data/model/MakeFitGroupMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/MyFitMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/MyFitDto.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/RequestRegisterFitGroupBodyDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/MakeFitGroupRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/RegisterFitGroupService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/MakeFitGroupNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/domain/model/RequestRegisterFitGroupBody.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/CertificationRecordRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/MakeFitGroupRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/MakeFitGroupUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt
=> FIt Group 생성 Networking 작업 완료 #17

app/src/main/java/com/fitmate/fitmate/data/repository/CertificationRecordRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/CertificationRecordService.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/CertificationTargetGroupService.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/MyFitService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/CertificationNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/MakeFitGroupNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/MyFitNetworkModule.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/RetrofitModule.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/CertificationRecordRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/CertificationRecordNetworkUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt
=> feature 실 서버와 연결 #77

app/src/main/java/com/fitmate/fitmate/data/model/MakeFitGroupMapper.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/MakeFitGroupUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/MakeGroupViewModel.kt, app/src/main/java/com/fitmate/fitmate/util/GroupCategory.kt
그룹 만들기 통신 구현 완료 및 인증 부분 테스트 수행중
=> feature 그룹 만들기 화면 post network #17

app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt, app/src/main/res/layout/fragment_certificate.xml
인증 진행 시 인증이 불가능한 상태(인증을 수행한지 24시간이 지나지 않은 상태)
++해당 주에 인증 횟수를 넘어도 오류가 발생하는지는 회의 후 확인이 필요한 상태
=> feature 운동 기록 화면 통신 issue #34

app/src/main/java/com/fitmate/fitmate/data/repository/VoteRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/VoteService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/VoteModule.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/VoteRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/VoteUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupProgressFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupVoteFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeMainFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/list/VoteViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/VoteViewModel.kt
투표 승인,
투표 내역 열람(개인 기준, 그룹 기준)
그룹 내 인원 운동 진척도
해당 기능들 실제 서버와 API 연결
=> 투표 및 그룹 진척도 기능 실제 서버와 연결 #77

app/src/main/java/com/fitmate/fitmate/data/model/dto/ChatDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/ChatRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/dao/ChatService.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/ChatRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/DBChatUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/ChattingViewModel.kt
서버 내 변수 변경에 따른 Chat API 에 대한 변경사항 적용 및 최적화
=> Chatting 서버 API 변경점 최적화 #30

app/src/main/java/com/fitmate/fitmate/data/model/dto/VoteDto.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupVoteFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupVoteViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt
그룹 투표 현황 화면 인증 사진 추가.
추후에 투표 찬반 dialog에도 추가할 예정
=> 그룹 투표 현황 화면 인증 사진 추가 #31

app/build.gradle.kts, app/src/main/java/com/fitmate/fitmate/MainActivity.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/LoginDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/LoginRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/LoginService.kt, app/src/main/java/com/fitmate/fitmate/di/networkModule/LoginModule.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/LoginRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/LoginUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt, app/src/main/java/com/fitmate/fitmate/util/ControlActivityInterface.kt, buildSrc/src/main/kotlin/AppConfig.kt, buildSrc/src/main/kotlin/Libraries.kt, buildSrc/src/main/kotlin/Versions.kt
로그인 시도 시 인가 코드를 붙혀서 보내주기만 하는 기본 기능에서
로그인 완료 시 받아오는 정보들에 대한 핸들링 여부 및
FCM 토큰에 대한 Api 변경점 미리 추가
=> 로그인 서버와 연결 후 로그인 작업 완료 #11

app/src/main/java/com/fitmate/fitmate/data/repository/LoginRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/LoginService.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/LoginRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/LoginUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt
=> FCM 토큰 전송 추가 #11

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/fitmate/fitmate/MyFirebaseMessagingService.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/util/ControlActivityInterface.kt, app/src/main/res/drawable/baseline_notifications_24.xml, app/src/main/res/values/strings.xml
토큰 발급  후 유저 정보에 post 및 알림 테스트 완료
=> fcm function #112

app/src/main/java/com/fitmate/fitmate/data/source/remote/LoginService.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/certificate/CertificateFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/GroupJoinFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/myfit/MyFitFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/CertificationViewModel.kt, app/src/main/res/layout/layout_test.xml
기존의 임시 userId를
로그인 완료 후에 받아오는 실제 유저아이디를 사용하도록 적용
[Certification, MyFit, Login, MakeGroup...]
=> 유저아이디 실제 로그인 후 적용 #11

app/src/main/java/com/fitmate/fitmate/data/source/remote/LoginService.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/ProfileFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/res/drawable/bg_profile.xml, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/layout/fragment_user_info.xml, app/src/main/res/navigation/nav_main_graph.xml, app/src/main/res/values/strings.xml
프로필 변경 추가 추후 elastic ip 변경 후 수정예정
=> Feat Profile Fragment into User Info #2

app/src/main/java/com/fitmate/fitmate/MainActivity.kt, app/src/main/java/com/fitmate/fitmate/data/model/MakeFitGroupMapper.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/LoginDto.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/RequestRegisterFitGroupBodyDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/LoginRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/LoginService.kt, app/src/main/java/com/fitmate/fitmate/domain/model/RequestRegisterFitGroupBody.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/LoginRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/LoginUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/GroupVoteFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/list/GroupVoteViewHolder.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/home/HomeFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/NicknameFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/onboarding/OnBoardingPermissionFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/ProfileFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/MakeGroupViewModel.kt, app/src/main/java/com/fitmate/fitmate/util/ControlActivityInterface.kt, app/src/main/res/layout/dialog_group_vote.xml, app/src/main/res/layout/item_vote.xml, app/src/main/res/navigation/nav_main_graph.xml
백앤드 측과 협의하여
기존의 로그인 방식 및 이벤트에 맞춰서 정의되도록 수정
=> 로그인 기능 정립 #11

app/build.gradle.kts, app/src/main/java/com/fitmate/fitmate/ChatActivity.kt, app/src/main/java/com/fitmate/fitmate/data/model/dto/RequestRegisterFitGroupBodyDto.kt, app/src/main/java/com/fitmate/fitmate/data/repository/ChatRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/repository/MakeFitGroupRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/dao/ChatDao.kt, app/src/main/java/com/fitmate/fitmate/domain/model/RequestRegisterFitGroupBody.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/ChatRepository.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MakeGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/mygroup/MyGroupFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/ChattingViewModel.kt, app/src/main/res/layout/activity_chat.xml, app/src/main/res/layout/fragment_chatting.xml, app/src/main/res/menu/chat_toolbar.xml, app/src/main/res/navigation/nav_chat_graph.xml, build.gradle.kts, settings.gradle.kts
=> 125 채팅 플로우 최적화 및 오류 해결

app/src/main/java/com/fitmate/fitmate/data/model/dto/LoginDto.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/category/CategoryFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/category/CategorySelectFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/ProfileFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt, app/src/main/res/layout/fragment_category_select.xml, app/src/main/res/layout/fragment_nickname.xml, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/layout/fragment_user_info.xml, app/src/main/res/navigation/nav_main_graph.xml
내 정보 화면 - 실제 로그인한 유저 정보 들어가도록 추가
정보 변경 화면 - 실제 유저 정보가 변경 요청이 되도록
카테고리 화면 - 카테고리 내부로 들어갔을 때 네비바 삭제 및 선택화면 디자인 변경
=> 내 정보 화면 및 정보 변경화면 데이터 수정 #2

app/src/main/java/com/fitmate/fitmate/presentation/ui/point/PointFragment.kt, app/src/main/res/layout/fragment_point.xml, app/src/main/res/layout/text_list_item.xml, app/src/main/res/navigation/nav_main_graph.xml, app/src/main/res/values/strings.xml
=> Feat add point fragment function complete

app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt
Get FitMate List 호출 시점 변경
toggle Drawer 함수 -> onCreate
=> Get FitMate List 호출 시점 변경 #125

app/src/main/java/com/fitmate/fitmate/presentation/ui/chatting/ChattingFragment.kt
observeFitMateList()를 onViewCreated에 선언하여 리스트 호출
=> 그룹 내 fitMate 정보 호출 시점 변경 #125

app/src/main/java/com/fitmate/fitmate/MainActivity.kt, app/src/main/java/com/fitmate/fitmate/data/repository/LoginRepositoryImpl.kt, app/src/main/java/com/fitmate/fitmate/data/source/remote/LoginService.kt, app/src/main/java/com/fitmate/fitmate/domain/repository/LoginRepository.kt, app/src/main/java/com/fitmate/fitmate/domain/usecase/LoginUseCase.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/login/LoginWebViewFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/ui/userinfo/UserInfoFragment.kt, app/src/main/java/com/fitmate/fitmate/presentation/viewmodel/LoginViewModel.kt, app/src/main/java/com/fitmate/fitmate/util/ControlActivityInterface.kt, app/src/main/res/layout/fragment_onboarding_first.xml, app/src/main/res/navigation/nav_main_graph.xml
로그인 로그아웃 회원탈퇴 플로우 오류 수정 및 변경
+ 로그인 화면에서 물리 Back 버튼 클릭 시 바로 종료되도록 변경
=> feature login withdraw #11
